export const SET_FRANCHISES_LIST_FILTERS = 'SET FRANCHISES LIST FILTERS';
export const SET_FRANCHISES_LIST_SORTING = 'SET FRANCHISES LIST SORTING';
export const SET_FRANCHISES_LIST_PAGE = 'SET FRANCHISES LIST PAGE';
export const SET_FRANCHISES_ITEMS_LIST_FILTERS = 'SET FRANCHISES ITEMS LIST FILTERS';
export const SET_FRANCHISES_ITEMS_LIST_SORTING = 'SET FRANCHISES ITEMS LIST SORTING';
export const SET_FRANCHISES_ITEMS_LIST_PAGE = 'SET FRANCHISES ITEMS LIST PAGE';
