export const SET_USERITEMS_LIST_FILTERS = 'SET USER_ITEMS LIST FILTERS';
export const SET_USERITEMS_LIST_SORTING = 'SET USER_ITEMS LIST SORTING';
export const SET_USERITEMS_LIST_PAGE = 'SET USER_ITEMS LIST PAGE';
