export const SET_LISTS_LIST_FILTERS = 'SET LISTS LIST FILTERS';
export const SET_LISTS_LIST_SORTING = 'SET LISTS LIST SORTING';
export const SET_LISTS_LIST_PAGE = 'SET LISTS LIST PAGE';
export const SET_LISTS_ITEMS_LIST_FILTERS = 'SET LISTS ITEMS LIST FILTERS';
export const SET_LISTS_ITEMS_LIST_SORTING = 'SET LISTS ITEMS LIST SORTING';
export const SET_LISTS_ITEMS_LIST_PAGE = 'SET LISTS ITEMS LIST PAGE';
